# Generated by Django 3.0.4 on 2020-03-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesRecommendationSystem', '0002_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requestMovie',
        ),
    ]
