# Generated by Django 3.0.4 on 2020-03-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesRecommendationSystem', '0003_auto_20200326_0634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requestMovie',
        ),
    ]
