# Generated by Django 3.0.4 on 2020-03-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesRecommendationSystem', '0005_requestmovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requestMovie',
        ),
    ]
