# Generated by Django 3.0.4 on 2020-04-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesRecommendationSystem', '0007_requestmoviemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
