# Generated by Django 3.0.4 on 2020-04-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesRecommendationSystem', '0009_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
